# Generated by Django 4.0.4 on 2022-06-07 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
